user:
  outputs:
    default:
      account: TVCOHUL-KF28575
      auth_type: password
      client_session_keep_alive: true
      connect_retries: 3
      connect_timeout: 30
      database: NORTHSTAR
      password: jevJepjydmah9cupja
      retry_on_database_errors: true
      role: ACCOUNTADMIN
      schema: dbt_northstar
      type: snowflake
      user: viveksuresh
      warehouse: transforming
  target: default
